GLEW_INCLUDE = /opt/local/include
GLEW_LIB = /opt/local/lib

main: main.o ShaderProgram.o ObjMesh.o
	g++ -o main $^ -framework GLUT -framework OpenGL -L$(GLEW_LIB) -lGLEW

.cpp.o:
	g++ -Wno-deprecated-declarations -c -o $@ $< -I$(GLEW_INCLUDE)

clean:
	rm -f main *.o
