GL_INCLUDE = /usr/X11R6/include
GL_LIB = /usr/X11R6/lib

baseopengl: baseopengl.o
	g++ -o baseopengl $^ -L$(GL_LIB) -lm -lGL -lglut -lGLEW

.cpp.o:
	g++ -std=gnu++0x -c -o $@ $< -I$(GL_INCLUDE)

clean:
	rm -f baseopengl *.o
